### ISSUE TITLE
Key size Error

### ISSUE THREAD

**Issue by Angu0083** [Shuuubhraj/AIOEDv1.0#1]
Hello, 

         I'm having difficulty in encrypting the text while selecting the Key sizes.

~# python3 Encrypt_Custom.py

 █████╗ ██╗ ██████╗ ███████╗██████╗ 
██╔══██╗██║██╔═══██╗██╔════╝██╔══██╗
███████║██║██║   ██║█████╗  ██║  ██║
██╔══██║██║██║   ██║██╔══╝  ██║  ██║
██║  ██║██║╚██████╔╝███████╗██████╔╝
╚═╝  ╚═╝╚═╝ ╚═════╝ ╚══════╝╚═════╝  v1.0

By : Rajput Shubhraj Singh
AIOED: ALL in One Encryption Decryption

Select a cipher mode:
1. AES
2. DES
3. 3DES
0. Exit
Enter your choice: 1
Selected cipher mode: AES

What would you like to do?
1. Encrypt
2. Decrypt
3. Clear
0. Go back
Enter your choice: 1

Enter the plaintext to encrypt: Demo

Enter the key (key length: 16, 24, or 32 bytes):
16

Invalid AES key length.
What would you like to do?
1. Encrypt
2. Decrypt
3. Clear
0. Go back
Enter your choice: 1   

Enter the plaintext to encrypt: Demo

Enter the key (key length: 16, 24, or 32 bytes):
24

Invalid AES key length.
What would you like to do?
1. Encrypt
2. Decrypt
3. Clear
0. Go back
Enter your choice:

**Comment by Shuuubhraj** [comment]
Hi @Angu0083 ,

Thank you for reaching out and using AIOED for encryption and decryption. Let me clarify how to correctly enter the key length and provide a solution to overcome this:

When the tool asks for the key length (16, 24, or 32 bytes), it's not asking for the number "16" or "24." Instead, it's expecting you to provide a key of the specified length in hexadecimal format.

For example, if you want to use a 16-byte key, you should enter a 32-character hexadecimal key. Here's an example: 00112233445566778899AABBCCDDEEFF.

Similarly, for a 24-byte key, you should enter a 48-character hexadecimal key, and for a 32-byte key, you should enter a 64-character hexadecimal key.

To overcome the issue:

Choose the desired key length (16, 24, or 32 bytes).
Convert your key into a hexadecimal format. You can use online converters if needed to do this.
Enter the hexadecimal key when prompted.
For instance, if you want to use a 16-byte key, convert it into a 32-character hexadecimal format and then enter it in the tool.

I hope this helps you overcome the issue. If you have any further questions or run into any more problems, please don't hesitate to ask for assistance. 

Best regards,
@Shuuubhraj 
Rajput Shubhraj Singh

**Comment by Angu0083** [comment]
Hello @Shuuubhraj 

           Thanks for your response. I tried a few sites, but it won't work for me.

           If possible, Share some online converters or demo in gif file.
